# Generated by Django 4.1.7 on 2023-03-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_customer_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("M", "Mobile"),
                    ("L", "Laptop"),
                    ("TW", "Top Wear"),
                    ("BW", "Bottom Wear"),
                    ("WW", "Wrist Watch"),
                    ("SH", "Shoes"),
                ],
                max_length=2,
            ),
        ),
    ]
