# Generated by Django 4.1.7 on 2023-03-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placedorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Packed", "Packed"),
                    ("On The Way", "On The Way"),
                    ("Delivered", "Delivered"),
                    ("Cancel", "Cancel"),
                ],
                default="Accepted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("M", "Mobile"),
                    ("L", "Laptop"),
                    ("TV", "Television"),
                    ("TW", "Top Wear"),
                    ("BW", "Bottom Wear"),
                    ("WW", "Wrist Watch"),
                    ("SH", "Shoes"),
                ],
                max_length=2,
            ),
        ),
    ]
